from flask import Flask, request, jsonify
from agents.workers.knowledge_base_builder_agent import KnowledgeBaseBuilderAgent
from shared.utils import setup_logger
import json
import sys
import uuid
from datetime import datetime, timezone

logger = setup_logger(__name__)
app = Flask(__name__)

agent = KnowledgeBaseBuilderAgent(
    agent_id="KnowledgeBaseBuilderAgent",
    supervisor_id="SupervisorAgent_Main"
)

logger.info("KnowledgeBaseBuilderAgent API server initialized")


class MessageCapture:
    def __init__(self):
        self.last_message = None
    
    def capture(self, message_dict):
        self.last_message = message_dict


message_capture = MessageCapture()


@app.route('/message', methods=['POST'])
def handle_message():
    try:
        if not request.is_json:
            return jsonify({
                "status": "error",
                "output": None,
                "error": {
                    "type": "INVALID_CONTENT_TYPE",
                    "message": "Content-Type must be application/json"
                }
            }), 400
        
        json_data = request.get_json()
        logger.info(f"Received Supervisor format message: intent={json_data.get('intent', 'unknown')}, request_id={json_data.get('request_id', 'unknown')[:8]}...")
        
        # Process message through agent (agent now handles Supervisor format natively)
        original_send = agent._send_json_message
        agent._send_json_message = message_capture.capture
        
        agent.handle_incoming_message(json.dumps(json_data))
        
        agent._send_json_message = original_send
        
        if message_capture.last_message:
            response_message = message_capture.last_message
            message_capture.last_message = None
            return jsonify(response_message), 200
        else:
            return jsonify({
                "status": "error",
                "output": None,
                "error": {
                    "type": "NO_RESPONSE",
                    "message": "No response generated by agent"
                }
            }), 500
            
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in request: {str(e)}")
        return jsonify({
            "status": "error",
            "output": None,
            "error": {
                "type": "INVALID_JSON",
                "message": f"Invalid JSON format: {str(e)}"
            }
        }), 400
    except Exception as e:
        logger.error(f"Error processing message: {str(e)}", exc_info=True)
        return jsonify({
            "status": "error",
            "output": None,
            "error": {
                "type": "INTERNAL_ERROR",
                "message": f"Internal server error: {str(e)}"
            }
        }), 500


@app.route('/health', methods=['GET'])
def health_check():
    try:
        # Create Supervisor format health check message
        health_check_message = {
            "request_id": str(uuid.uuid4()),
            "agent_name": agent.agent_id,
            "intent": "health_check",
            "input": {
                "text": "",
                "metadata": {}
            },
            "context": {
                "user_id": "system",
                "conversation_id": None,
                "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            }
        }
        
        original_send = agent._send_json_message
        agent._send_json_message = message_capture.capture
        
        agent.handle_incoming_message(json.dumps(health_check_message))
        
        agent._send_json_message = original_send
        
        if message_capture.last_message:
            response = message_capture.last_message
            message_capture.last_message = None
            return jsonify(response), 200
        else:
            # Fallback Supervisor format response
            from datetime import datetime, timezone
            timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            return jsonify({
                "request_id": health_check_message["request_id"],
                "agent_name": agent.agent_id,
                "status": "success",
                "output": {
                    "result": "I'm up and ready",
                    "confidence": 1.0,
                    "details": f"Health check successful at {timestamp}"
                },
                "error": None
            }), 200
            
    except Exception as e:
        logger.error(f"Error in health check: {str(e)}", exc_info=True)
        return jsonify({
            "status": "error",
            "output": None,
            "error": {
                "type": "HEALTH_CHECK_FAILED",
                "message": f"Health check failed: {str(e)}"
            }
        }), 500


@app.route('/tasks', methods=['GET'])
def get_tasks():
    try:
        if not agent.db:
            return jsonify({
                "status": "error",
                "error": {
                    "type": "DATABASE_NOT_INITIALIZED",
                    "message": "Database not initialized"
                }
            }), 500
        
        tasks = agent.db.list_tasks()
        return jsonify({
            "status": "success",
            "tasks": tasks,
            "count": len(tasks)
        }), 200
    except Exception as e:
        logger.error(f"Error getting tasks: {str(e)}", exc_info=True)
        return jsonify({
            "status": "error",
            "error": {
                "type": "INTERNAL_ERROR",
                "message": f"Error retrieving tasks: {str(e)}"
            }
        }), 500


@app.route('/', methods=['GET'])
def root():
    return jsonify({
        "service": "KnowledgeBaseBuilderAgent API",
        "version": "0.1.0",
        "agent_id": "KnowledgeBaseBuilderAgent",
        "format": "Supervisor format (native)",
        "endpoints": {
            "POST /message": "Handle incoming Supervisor format JSON messages",
            "GET /health": "Health check endpoint (returns Supervisor format)",
            "GET /tasks": "Get all tasks from database",
            "GET /": "API information"
        },
        "supervisor_format": {
            "request": {
                "request_id": "string (required)",
                "agent_name": "KnowledgeBaseBuilderAgent (required)",
                "intent": "create_task | health_check (required)",
                "input": {
                    "text": "string (required for create_task)",
                    "metadata": "object (optional)"
                },
                "context": {
                    "user_id": "string (required)",
                    "conversation_id": "string (optional)",
                    "timestamp": "string (optional)"
                }
            },
            "response_success": {
                "request_id": "string",
                "agent_name": "string",
                "status": "success",
                "output": {
                    "result": "string",
                    "confidence": "number",
                    "details": "object"
                },
                "error": null
            },
            "response_error": {
                "status": "error",
                "output": null,
                "error": {
                    "type": "string",
                    "message": "string"
                }
            }
        },
        "intents": ["create_task", "health_check"]
    }), 200


if __name__ == '__main__':
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5000
    host = sys.argv[2] if len(sys.argv) > 2 else '127.0.0.1'
    
    logger.info(f"Starting API server on {host}:{port}")
    app.run(host=host, port=port, debug=False)

